# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portctl < Formula
  desc "Find and free processes binding a TCP port"
  homepage "https://github.com/chasesaurabh/portctl"
  version "1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0/portctl_1.0_darwin_amd64.tar.gz"
      sha256 "f6ed999b4304a827a29133b4d0ee275e97510fdcfd6cb09d2613517e4e563e7e"

      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0/portctl_1.0_darwin_arm64.tar.gz"
      sha256 "9ace28ed10ae8cb89806b95251cd41afa49d37d4439c3e617e492b54fc84b434"

      def install
        bin.install "portctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0/portctl_1.0_linux_amd64.tar.gz"
      sha256 "733bcf642b0624dedc6a5c9542eeae58bac3bc80c23e997cfe70cf9d7238a047"
      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0/portctl_1.0_linux_arm64.tar.gz"
      sha256 "7334fd34f1a4ec02e1aa0a1fe23c085941d8b91d94c37d9be6c26c53fe4077e7"
      def install
        bin.install "portctl"
      end
    end
  end

  test do
    system "#{bin}/portctl", "--help"
  end
end
