# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portctl < Formula
  desc "Find and free processes binding a TCP port"
  homepage "https://github.com/chasesaurabh/portctl"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.2/portctl_1.0.2_darwin_amd64.tar.gz"
      sha256 "df68f1c059e47ccba13231cec4df3768b4c136046e8865a90d93f726ac42a755"

      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.2/portctl_1.0.2_darwin_arm64.tar.gz"
      sha256 "1973e16d77a74c0ece422f0c0d16ec07d69736c6502c1efbff1200f8dbc10de9"

      def install
        bin.install "portctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.2/portctl_1.0.2_linux_amd64.tar.gz"
      sha256 "f5225af02cb3d4c0acfebd1ea0acb1479f6a0c3e5692ddd676fb71fd50d465ed"
      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.2/portctl_1.0.2_linux_arm64.tar.gz"
      sha256 "1c68e6a7309bd47e72bfa069a84e124d8f6bd7e1777b89aa8c359c27f04734e2"
      def install
        bin.install "portctl"
      end
    end
  end

  test do
    system "#{bin}/portctl", "--help"
  end
end
