# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portctl < Formula
  desc "Find and free processes binding a TCP port"
  homepage "https://github.com/chasesaurabh/portctl"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.3/portctl_1.0.3_darwin_amd64.tar.gz"
      sha256 "a41737cb1a9f1d6947512386656e63bd3e561d1c179a99f7f35028a485b87bfb"

      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.3/portctl_1.0.3_darwin_arm64.tar.gz"
      sha256 "082a7839684671fe05f01f893be3603553a03a46c13918f9925b5f1f345e9879"

      def install
        bin.install "portctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.3/portctl_1.0.3_linux_amd64.tar.gz"
      sha256 "bfd395e966c13ab9567836c3d71bc57ff9b6b162f6a008a0010275ab3ecc7763"
      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v1.0.3/portctl_1.0.3_linux_arm64.tar.gz"
      sha256 "0512d42df87fa2c65208bf03028f8b6db2c8e2255a2da85532b62939f07fa6da"
      def install
        bin.install "portctl"
      end
    end
  end

  test do
    system "#{bin}/portctl", "--help"
  end
end
