# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portctl < Formula
  desc "Find and free processes binding a TCP port"
  homepage "https://github.com/chasesaurabh/portctl"
  version "0.1.2-SNAPSHOT-251465c"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chasesaurabh/portctl/releases/download/v0.1.2/portctl_0.1.2-SNAPSHOT-251465c_darwin_amd64.tar.gz"
      sha256 "833f44dedb960c5c4d6b07b68d26d7ca9fa417c768d679a53059a422768bfe14"

      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chasesaurabh/portctl/releases/download/v0.1.2/portctl_0.1.2-SNAPSHOT-251465c_darwin_arm64.tar.gz"
      sha256 "7da27fc18c86475d49a823a7bceabaeab11d78b0dfda5dce62542ac4521fc7dc"

      def install
        bin.install "portctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v0.1.2/portctl_0.1.2-SNAPSHOT-251465c_linux_amd64.tar.gz"
      sha256 "8a24f63577c030fabfbfaf753b1ce29a0ef114e52617e622097bd1ad932a0227"
      def install
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chasesaurabh/portctl/releases/download/v0.1.2/portctl_0.1.2-SNAPSHOT-251465c_linux_arm64.tar.gz"
      sha256 "a0fcb50f8190cf6997066dac32245b17a3ddd21dfa04d3efdd150ff98ac49bce"
      def install
        bin.install "portctl"
      end
    end
  end

  test do
    system "#{bin}/portctl", "--help"
  end
end
